---

  - name: Backup playbook
    hosts: all
    become: true
    tasks:
      - name: Backup db logs
        archive:
          path: /var/log/mariadb/
          dest: /var/log/mariadb.tar.bz2
          format: bz2
        when: inventory_hostname in groups['uat']


      - name: Backup openvswitch logs
        archive:
          path: /var/log/openvswitch
          dest: /var/log/openvswitch.tar.bz2
          format: bz2
        when: inventory_hostname in groups['dev']
