apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
  labels:
    name: backend
    app: webserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: backend
        app: webserver
    spec:
      containers:
        - name: backend
          image: docker.io/httpd:2.4
          ports: 
            - containerPort: 80
              name: http
              protocol: TCP
