apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
    app: webserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: frontend
        app: webserver
    spec:
      containers:
        - name: frontend
          image: docker.io/httpd:2.4
          ports: 
            - containerPort: 80
              name: http
              protocol: TCP
