apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
    app: webserver
spec:
  ports:
    - port: 9080
      name: http
      targetPort: 80
  selector:
    name: frontend
    app: webserver
  type: ClusterIP
