apiVersion: "v1"
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontend
    app: webserver
spec:
  containers:
    - name: frontend
      image: docker.io/httpd:2.4
      ports:
        - containerPort: 80
          protocol: TCP
