apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: webserver
spec:
  containers:
    - name: web
      image: docker.io/httpd:2.4
      ports:
        - containerPort: 80
          protocol: TCP
  serviceAccountName: worker

---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: webserver
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 80
  selector:
    name: web
    app: webserver
