apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics

spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
 
  nfs:
    path: /shared/metrics
    server: registry.lab.example.com
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: metrics-1
    namespace: openshift-infra
