kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    type: local
spec:
  capacity: 
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/openshift/work/init
