apiVersion: v1
kind: ReplicationController
metadata:
  name: database
  labels:
    name: database
    app: gcloud

spec:
  replicas: 1
  template:
    metadata:
      name: database
      labels:
        name: database
        app: gcloud
    spec:
      containers:

        - name: mysql 
          image: mysql:5.6 
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: "linux"
---

apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    name: database
    app: gcloud
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32000
  selector:
    name: database
    app: gcloud
