apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    name: wordpress
    app: content_server
    
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 80

  selector:
    name: wordpress
    app: content_server
