apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-claim
  labels:
    app: content_server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
    volumeName: wordpress-storage
