apiVersion: v1
kind: DeploymentConfig
metadata:
  name: python-dc
  labels:
    name: python
    app: pyserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: python
        app: pyserver
    spec:
      containers:
        - name: python
          image: cherry/web:v1.0
          ports: 
            - containerPort: 8000
              name: http
              protocol: TCP
