apiVersion: "v1"
kind: Pod
metadata:
  name: python
  labels:
    name: python
    app: pyserver
spec:
  containers:
    - name: python
      image: cherry/web:v1.0
      ports:
        - containerPort: 8000
          protocol: TCP
