apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    name: python
    app: pyserver
    
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8000

  selector:
    name: python
    app: pyserver
