apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceAccountName: mysql
  containers:
    - name: mysql
      image: docker.io/mysql:5.6
      ports:
        - name: dbport
          protocol: TCP
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55

        - name: MYSQL_DATABASE
          value: wordpress

        - name: MYSQL_USER
          value: user1

        - name: MYSQL_PASSWORD
          value: userpa55
     
      volumeMounts:
        - 
          mountPath: /var/lib/mysql
          name: dbvolume

  volumes:
    - 
      name: dbvolume
      persistentVolumeClaim:
        claimName: mysql-pvc 
