apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv

spec:
  capacity: 
    storage: 256Mi

  accessModes:
    - ReadWriteOnce
  
  nfs:
    path: /shared/mysql
    server: registry.lab.example.com
