apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  serviceAccountName: wordpress
  containers:
    - name: wordpress
      image: docker.io/wordpress:5.0
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      
      env: 
        - name: WORDPRESS_DB_HOST
#         value: 172.30.25.199
          value: mysql.wordpress.svc.cluster.local

        - name: WORDPRESS_DB_USER
          value: user1

        - name: WORDPRESS_DB_PASSWORD
          value: userpa55

        - name: WORDPRESS_DB_NAME
          value: wordpress

#     volumeMounts:
#       - mountPath: /usr/local/apache2/htdocs
#       - mountPath: /var/www/html
#         name: htdocs
# volumes:
#   - name: htdocs
#     persistentVolumeClaim:
#       claimName: wordpress-pvc
