apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv

spec:
  capacity: 
    storage: 256Mi

  accessModes:
    - ReadOnlyMany
  
  nfs:
    path: /shared/wordpress
    server: registry.lab.example.com
