apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  nodeSelector:
    region: uat
  containers:
    - name: redis
      image: docker.io/redis:3.2 
      ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
      env:
        - name: "MACHINE"
          value: "redis-linux"
    - name: http
      image: docker.io/httpd:2.4 
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      env:
        - name: "REDIS_HOST"
          value: "localhost"
