apiVersion: v1
kind: PersistentVolume
metadata:
  name: probes-pv

spec:
  capacity: 
    storage: 256Mi

  accessModes:
    - ReadOnlyMany
  
  nfs:
    path: /shared/probes
    server: registry.lab.example.com
