apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: webserver
    
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 80
      nodePort: 31100
  selector:
    name: web
    app: webserver
  type: NodePort
