apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: webserver
spec:
  containers:
    - name: web
      image: docker.io/httpd:2.4
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: my-vol
  volumes:
    - name: my-vol
      hostPath:
        path: /var/lib/my-data
