apiVersion: v1
kind: LimitRange
metadata:
  name: newtown
spec:
  limits:
    - type: "Pod"
      max: 
        cpu: 500m
        memory: 256Mi
      min:
        cpu: 200m
        memory: 128Mi
        
    - type: "Container" 
      default:
        cpu: 200m
        memory: 128Mi
