apiVersion: v1
kind: Pod
metadata:
  name: kuruwita
  labels:
    app: kelani
spec:
  containers:
    - name: httpd
      image: docker.io/httpd:2.4
      ports:
        - name: http
          protocol: TCP
          containerPort: 80
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
