heat_template_version: 2016-10-14
description: Auto Scaling a custom webserver using cpu_util meter

parameters:
  key_name:
    type: string
    default: web-keypair
  instance_name:
    type: string
    default: web-server
  instance_flavor:
    type: string
    default: m2.small
  image_name:
    type: string
    default: web-image
  public_net:
    type: string
  private_net:
    type: string
  private_subnet:
    type: string
  initial_capacity:
    type: number
    default: 1
  cooldown_policy_seconds:
    type: number
    default: 30
  asg_group_min_size:
    type: number
    default: 1
  asg_group_max_size:
    type: number
    default: 3

resources:
  random:
    type: OS::Heat::RandomString
    properties:
      length: 2

  web_scaler:
    type: OS::Heat::AutoScalingGroup
    properties:
      desired_capacity: { get_param: initial_capacity }
      cooldown: { get_param: cooldown_policy_seconds }
      max_size: { get_param: asg_group_max_size }
      min_size: { get_param: asg_group_min_size }
      resource:
        type: My::Server::Custom::WebServer
        properties:
          instance_name: { list_join: ['-', [ { get_param: instance_name }, { get_attr: [ random, value ] } ] ] }
          instance_flavor: { get_param: instance_flavor }
          image_name: { get_param: image_name }
          key_name: { get_param: key_name }
          public_net: { get_param: public_net }
          private_net: { get_param: private_net }
          private_subnet: { get_param: private_subnet }
          # IMPORTANT!! without this metadata the instances don't have a stack ID
          instance_metadata: { "metering.stack" : { get_param: "OS::stack_id" } }

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: web_scaler }
      cooldown: { get_param: cooldown_policy_seconds }
      scaling_adjustment: 1

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: web_scaler }
      cooldown: { get_param: cooldown_policy_seconds }
      scaling_adjustment: -1


  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if the average CPU > 30 % for 70 secnods
      meter_name: cpu_util
      statistic: avg
      period: 70
      evaluation_periods: 1
      threshold: 30
      alarm_actions: 
        - { get_attr: [ scaleup_policy, alarm_url ] }
      comparison_operator: gt 
      matching_metadata: { 'metadata.user_metadata.stack': { get_param: "OS::stack_id" } }

  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-down if the average CPU < 15% for 600 secnods
      meter_name: cpu_util
      statistic: avg
      period: 600
      evaluation_periods: 1
      threshold: 15
      alarm_actions: 
        - { get_attr: [ scaledown_policy, alarm_url ] }
      comparison_operator: lt 
      matching_metadata: { 'metadata.user_metadata.stack': { get_param: "OS::stack_id" } }

outputs:
  web_private_ip_asg:
    description: IP address
    value: { get_attr: [ web_scaler, outputs_list, web_private_ip ]}

  web_public_ip_asg:
    description: IP address
    value: { get_attr: [ web_scaler, outputs_list, web_public_ip ] }

  website_url_asg:
    description: external URL 
    value: { get_attr: [ web_scaler, outputs_list, website_url ] }

