apiVersion: v1
kind: ReplicationController
metadata:
  name: mangosteen
  labels:
    name: mangosteen
    app: docker-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: mangosteen
        app: docker-demo
    spec:
      containers:
        - name: web
          image: mangosteen/web:v1.0
          ports: 
            - containerPort: 80
              name: http
              protocol: TCP
